### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by predators46** [chandelures/luci-app-simple-clash#38]

**Comment by chandelures** [comment]
@predators46 

This repository is an application in luci, simmilar to `luci-app-adblock`. Once installed on OpenWrt, you can access it through the Luci web interface as:

![image](https://github.com/chandelures/luci-app-simple-clash/assets/45688491/6afc7aea-4b9f-4f34-a674-3f3d7b07f7ba)

From there, you can import your personal Clash configuration using either the `static` or `URL` method. After importing, you can enable the service.

**Comment by predators46** [comment]
@chandelures 
can you please share your settings in config.yaml it looks like you didn't include those. I don't understand entering static and url configurations
